base_url = "/build/"
title = "Gluon docs"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
logo = "https://twemoji.maxcdn.com/v/13.0.1/svg/1f4e6.svg"
release = "https://api.github.com/repos/pulse-browser/build/releases/latest"
